version: 0.2

env:
  secrets-manager:
    TOKEN: loginToken:tokenForZap

#Dynamic Application Security Scan (DAST scan) using OWASP ZAP

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y wget openjdk-11-jdk

  build:
    commands:
      - echo "Starting DAST scan using OWASP ZAP..."
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
      - tar -xvf ZAP_2.16.0_Linux.tar.gz
      - cd ZAP_2.16.0
      - ./zap.sh -cmd -port 8081 -quickurl https://www.example.com/?login=$TOKEN -quickprogress
      - echo "ZAP scan completed successfully."

  post_build:
    commands:
      - echo "Build and scan completed!"
